<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>Condor.Escritorio</RootNamespace>
    <AssemblyName>CondorVentas</AssemblyName>
    <Version>0.1.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Condor.Presentacion\Condor.Presentacion.csproj" />
  </ItemGroup>

</Project>
